version: '2'
services:

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass

  redis:
    image: redis
    ports:
    - "6379:6379"

  worker:
    image: ultrasearch
    command: ['celery', '-A', 'ingest.tasks', 'worker', '-l', 'info']
    environment:
      - BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
      - RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbitmq
      - redis

  flower:
    image: mher/flower
    environment:
      - BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
      - RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - worker
    ports:
      - "5555:5555"
