apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-fetch
spec:
  schedule: "* 19 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ultrasearch-app
          automountServiceAccountToken: false
          containers:
          - name: cron-fetch
            image: pdbaines83/ultrasearch:0.0.1
            imagePullPolicy: IfNotPresent
            command: ["/bin/bash", "-c", "python run_celery.py && curl -X POST http://localhost:15020/quitquitquit"]
            env:
              - name: BROKER_URL
                valueFrom:
                  secretKeyRef:
                    name: broker
                    key: url
                    optional: false
              - name: CELERY_REMOTE
                value: "true"
              - name: RESULT_BACKEND
                value: redis://redis:6379/0
              - name: SOURCE_AHOTU
                value: https://www.ahotu.com/advanced-search.json
              - name: SOURCE_ULTRASIGNUP
                value: https://ultrasignup.com/service/events.svc/closestevents
              - name: SUPABASE_KEY
                valueFrom:
                  secretKeyRef:
                    name: supabase
                    key: key
                    optional: false
              - name: SUPABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: supabase
                    key: url
                    optional: false
          restartPolicy: OnFailure
