apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: flower-ui
    app: flower-ui
    version: "0.0.1"
  name: flower-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flower-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: flower-ui
        app: flower-ui
        version: "0.0.1"
    spec:
      serviceAccountName: ultrasearch-app
      automountServiceAccountToken: false
      containers:
        - env:
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: broker
                  key: url
                  optional: false
            - name: FLOWER_BROKER_API_URL
              valueFrom:
                secretKeyRef:
                  name: broker
                  key: management_url
                  optional: false
            - name: FLOWER_BASIC_AUTH
              valueFrom:
                secretKeyRef:
                  name: flower
                  key: auth
                  optional: false
            - name: RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: auth_url
                  optional: false
          image: mher/flower
          command: ["celery"]
          args: ["flower", "--url_prefix=flower", "--broker_api=$(FLOWER_BROKER_API_URL)"]
          name: flower-ui
          ports:
            - containerPort: 5555
          resources: {}
      restartPolicy: Always
status: {}
