name: build-and-test

on:
  push:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            pdbaines83/ultrasearch:${{ github.sha }}

      -
        name: Checkout
        uses: actions/checkout@v2

      -
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: hub.docker.com
          image: pdbaines83/ultrasearch:${{ github.sha }}
          run: |
            pytest

      -
        uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_CLUSTER_URL }}
          k8s-secret: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRET }}
        id: setcontext

      -
        name: deploy
        uses: Azure/k8s-deploy@v3.1
        with:
          namespace: ultrasearch
          manifests: |
            .gitops
          images: pdbaines83/ultrasearch:${{ github.sha }}
          strategy: basic
