name: deploy

on:
  workflow_run:
    workflows: ["build-and-test"]
    branches: [main]
    types:
      - completed

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      -
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
        id: setcontext

      -
        name: deploy
        uses: Azure/k8s-deploy@v3.1
        with:
          namespace: 'ultrasearch'
          manifests: |
            .gitops
          images: 'pdbaines83/ultrasearch:${{ github.sha }}'
